plugins {
    id 'com.android.application'
}

android {
    namespace 'com.clearbook'
    compileSdk 34

    defaultConfig {
        applicationId "com.clearbook"
        minSdk 24
        targetSdk 34
        versionCode 11
        versionName "2.0"
    }

    signingConfigs {
        release {
            storeFile file('debug.keystore')
            storePassword 'clearbook123'
            keyAlias 'clearbook'
            keyPassword 'clearbook123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}
